"""empty message

Revision ID: 021cc25c0f85
Revises: 8700955c3a60
Create Date: 2020-03-11 15:34:54.353142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021cc25c0f85'
down_revision = '8700955c3a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'suggested_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('suggested_answer', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
