"""empty message

Revision ID: 381e956d3a00
Revises: 8d0c633770d9
Create Date: 2020-02-24 22:12:43.073955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381e956d3a00'
down_revision = '8d0c633770d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('multiple_choice_topic', 'option_d')
    op.drop_column('multiple_choice_topic', 'dunno')
    op.drop_column('multiple_choice_topic', 'fifth')
    op.add_column('topic', sa.Column('points', sa.Integer(), nullable=True))
    op.drop_column('topic', 'suggested_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('suggested_answer', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('topic', 'points')
    op.add_column('multiple_choice_topic', sa.Column('fifth', sa.VARCHAR(length=64), nullable=True))
    op.add_column('multiple_choice_topic', sa.Column('dunno', sa.VARCHAR(length=64), nullable=True))
    op.add_column('multiple_choice_topic', sa.Column('option_d', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
