"""empty message

Revision ID: 8700955c3a60
Revises: af3c29ebf869
Create Date: 2020-03-10 14:20:28.012364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8700955c3a60'
down_revision = 'af3c29ebf869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'suggested_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('suggested_answer', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
