"""empty message

Revision ID: aa45a33ab22f
Revises: c89261166db7
Create Date: 2020-02-24 13:59:51.904942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa45a33ab22f'
down_revision = 'c89261166db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multiple_choice_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=64), nullable=True),
    sa.Column('option_a', sa.String(length=64), nullable=True),
    sa.Column('option_b', sa.String(length=64), nullable=True),
    sa.Column('option_c', sa.String(length=64), nullable=True),
    sa.Column('dunno', sa.String(length=64), nullable=True),
    sa.Column('answer', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.Boolean(), nullable=True),
    sa.Column('user_answer', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multiple_choice_topic_question'), 'multiple_choice_topic', ['question'], unique=False)
    op.alter_column('topic', 'user_answer',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('topic', 'suggested_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('suggested_answer', sa.VARCHAR(length=64), nullable=True))
    op.alter_column('topic', 'user_answer',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_index(op.f('ix_multiple_choice_topic_question'), table_name='multiple_choice_topic')
    op.drop_table('multiple_choice_topic')
    # ### end Alembic commands ###
