"""empty message

Revision ID: f3d0f1f8b8b0
Revises: 80f0e2ef873f
Create Date: 2020-03-02 15:20:45.769760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d0f1f8b8b0'
down_revision = '80f0e2ef873f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('resource_url', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_title'), 'resource', ['title'], unique=False)
    op.drop_index('ix_multiple_choice_topic_question', table_name='multiple_choice_topic')
    op.drop_table('multiple_choice_topic')
    op.add_column('topic', sa.Column('page', sa.String(length=100), nullable=True))
    op.add_column('topic', sa.Column('unit', sa.String(length=8), nullable=True))
    op.drop_column('topic', 'suggested_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('suggested_answer', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('topic', 'unit')
    op.drop_column('topic', 'page')
    op.create_table('multiple_choice_topic',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=64), nullable=True),
    sa.Column('option_a', sa.VARCHAR(length=64), nullable=True),
    sa.Column('option_b', sa.VARCHAR(length=64), nullable=True),
    sa.Column('option_c', sa.VARCHAR(length=64), nullable=True),
    sa.Column('dunno', sa.VARCHAR(length=64), nullable=True),
    sa.Column('answer', sa.VARCHAR(length=64), nullable=True),
    sa.Column('outcome', sa.BOOLEAN(), nullable=True),
    sa.Column('user_answer', sa.VARCHAR(length=64), nullable=True),
    sa.Column('fifth', sa.VARCHAR(length=64), nullable=True),
    sa.Column('option_d', sa.VARCHAR(length=64), nullable=True),
    sa.CheckConstraint('outcome IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_multiple_choice_topic_question', 'multiple_choice_topic', ['question'], unique=False)
    op.drop_index(op.f('ix_resource_title'), table_name='resource')
    op.drop_table('resource')
    # ### end Alembic commands ###
